plugins {
	id 'java-library'
	id 'org.springframework.boot'
}

dependencies {
	implementation project(':obelix-common')
	implementation project(':obelix-quarry-api')
	implementation project(':obelix-basket-api')

	testImplementation testFixtures(project(':obelix-common'))
}

tasks.named("bootBuildImage") {
	def registry = System.getenv("IMAGE_REGISTRY")
	imageName = registry ? "${registry}/obelix-webshop" : "obelix/webshop"
}

test {
	useJUnitPlatform()
	systemProperty 'spring.profiles.include', '!integration'
}
