plugins {
	id 'java-library'
	id 'org.springframework.boot'
	id 'org.springdoc.openapi-gradle-plugin'

	id "org.asciidoctor.jvm.convert" version "4.0.5"
}

configurations {
	asciidoctorExt
}

dependencies {
	implementation project(':obelix-common')
	implementation project(':obelix-quarry-api')
	implementation project(':obelix-basket-api')

	testImplementation testFixtures(project(':obelix-common'))

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// --- Spring REST Docs ---
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
	asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
}

ext {
	snippetsDir = file('resources/generated-snippets')
}

apply from: rootProject.file('gradle/bootBuildImage-versioning.gradle')
configureBootBuildImageVersioning(tasks.named("bootBuildImage"), "obelix-webshop", "obelix/webshop")

test {
	useJUnitPlatform()
}

tasks.named("forkedSpringBootRun") {
	dependsOn ':obelix-common:jar'
	dependsOn ':obelix-quarry-api:jar'
	dependsOn ':obelix-basket-api:jar'
	javaLauncher = javaToolchains.launcherFor {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

tasks.named('test') {
	// keep this if you already have it globally, but it's safe here:
	useJUnitPlatform()

	// tell Gradle tests write snippets here
	outputs.dir snippetsDir
}

tasks.named('asciidoctor') {
	inputs.dir snippetsDir
	configurations 'asciidoctorExt'
	dependsOn tasks.named('test')
}

// Put generated docs into the boot jar under /static/docs
tasks.named('bootJar') {
	dependsOn tasks.named('asciidoctor')
	from(tasks.named('asciidoctor').get().outputDir) {
		into 'static/docs'
	}
}

openApi {
	apiDocsUrl.set("http://localhost:8080/v3/api-docs")
	outputDir.set(file("$buildDir/docs"))
}
