/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for BasketController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { BasketItem, RequestOptions, BasketDto } from "../models";

@Injectable({ providedIn: "root" })
export class BasketControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    offer(basketItem: BasketItem, observe?: 'body', options?: RequestOptions<'blob'>): Observable<BasketDto>;
    offer(basketItem: BasketItem, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<BasketDto>>;
    offer(basketItem: BasketItem, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<BasketDto>>;
    offer(basketItem: BasketItem, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/basket/offer`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, basketItem, requestOptions);
    }

    exchangeFor(menhirId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    exchangeFor(menhirId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    exchangeFor(menhirId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    exchangeFor(menhirId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/basket/buy/${menhirId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    leave(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    leave(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    leave(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    leave(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/basket`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
