/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { BasketControllerService } from "./basketController.service";
export { MenhirControllerService } from "./menhirController.service";
export { WebshopControllerService } from "./webshopController.service";
