/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for MenhirController controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, MenhirDto } from "../models";

@Injectable({ providedIn: "root" })
export class MenhirControllerService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllMenhirs(observe?: 'body', options?: RequestOptions<'blob'>): Observable<Array<MenhirDto>>;
    getAllMenhirs(observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<Array<MenhirDto>>>;
    getAllMenhirs(observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<Array<MenhirDto>>>;
    getAllMenhirs(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/menhirs`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    getMenhirById(menhirId: string, observe?: 'body', options?: RequestOptions<'blob'>): Observable<MenhirDto>;
    getMenhirById(menhirId: string, observe?: 'response', options?: RequestOptions<'blob'>): Observable<HttpResponse<MenhirDto>>;
    getMenhirById(menhirId: string, observe?: 'events', options?: RequestOptions<'blob'>): Observable<HttpEvent<MenhirDto>>;
    getMenhirById(menhirId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/menhirs/${menhirId}`;

        const requestOptions: any = {
            observe: observe as any,
            responseType: 'blob' as 'blob',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
