ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]
== Deployment View

This chapter describes the **technical infrastructure** required to run the system and
how software building blocks are mapped onto that infrastructure.

Focus on **architecturally relevant deployment aspects** and keep the descriptions abstract
so teams can fill in details later.

---

=== Infrastructure Level 1 – Overview

==== Overview Diagram

[plantuml, deployment-level1, svg]
----
@startuml
node "<Environment / Location 1>" {
  node "<Server / VM / Container 1>"
  node "<Server / VM / Container 2>"
}

node "<Environment / Location 2>" {
  node "<Server / VM / Container 3>"
}

"<Server / VM / Container 1>" --> "<Server / VM / Container 2>" : <Connection / Protocol>
"<Server / VM / Container 1>" --> "<Server / VM / Container 3>" : <Connection / Protocol>
@enduml
----

==== Motivation

TODO:  
Explain **why this deployment structure is used**, e.g.:

* Scalability
* Fault tolerance
* Geographical distribution
* Separation of environments (dev/test/prod)

==== Quality and/or Performance Features

TODO:  
Document any relevant **non-functional aspects**, e.g.:

* Availability
* Throughput / latency
* Redundancy / failover
* Resource requirements (CPU, memory, storage)

==== Mapping of Building Blocks to Infrastructure

[cols="1,2",options="header"]
|===
|Building Block |Infrastructure Element / Node

|<Building Block 1>
|<Server / VM / Container / Node>

|<Building Block 2>
|<Server / VM / Container / Node>

|<Building Block n>
|<Server / VM / Container / Node>
|===

---

=== Infrastructure Level 2 – Internal Structure

Level 2 zooms into **selected infrastructure elements** from Level 1.  
Document **complex or critical elements** only.

==== <Infrastructure Element 1>

==== Diagram

[plantuml, infra-element1, svg]
----
@startuml
node "<Infrastructure Element 1>" {
  node "<Internal Component 1>"
  node "<Internal Component 2>"
}

"<Internal Component 1>" --> "<Internal Component 2>" : <Connection / Protocol>
@enduml
----

==== Motivation

TODO:  
Explain why this element is **relevant to document**, e.g.:

* Complex topology
* Multiple services deployed
* Performance-critical paths

==== Mapping of Building Blocks to Internal Components

[cols="1,2",options="header"]
|===
|Building Block |Mapped Component

|<Building Block A>
|<Internal Component 1>

|<Building Block B>
|<Internal Component 2>
|===

==== <Infrastructure Element 2>

(copy template above)

...

==== <Infrastructure Element n>

(copy template above)
