/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface BasketItem {
    name?: string;
    count?: number;
}

export interface BasketDto {
    items?: Array<BasketItem>;
}

export interface MenhirDto {
    id?: string;
    weight?: number;
    stoneType?: string;
    decorativeness?: 'PLAIN' | 'SIMPLE' | 'DECORATED' | 'ORNATE' | 'MASTERWORK';
    description?: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
